project_id = "kpgseyfkucnnzdaoqjdq"

[functions.vapi-assistant-request]
verify_jwt = false

[functions.vapi-end-of-call]
verify_jwt = false

[functions.vapi-create-appointment]
verify_jwt = false

[functions.send-whatsapp-confirmation]
verify_jwt = false

[functions.vapi-buy-number]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.accrue-referral-balance]
verify_jwt = false

[functions.vapi-join-queue]
verify_jwt = false

[functions.vapi-take-message]
verify_jwt = false

[functions.send-whatsapp-queue-notification]
verify_jwt = false

[functions.nxtup-events]
verify_jwt = false

[functions.whatsapp-inbound]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false
